# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-07 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_friend_current_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
