# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-11 09:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0030_auto_20171211_0814'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('meeting_date', models.DateTimeField()),
                ('details', models.TextField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Post')),
            ],
        ),
    ]
