# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-12 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0032_meeting_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, choices=[('Food', 'Food'), ('Transport', 'Transport'), ('IT', 'IT'), ('Logistics', 'Logistics'), ('Other', 'Other')], max_length=9),
        ),
    ]
