# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-13 13:55
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0034_auto_20171212_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='author',
            field=models.ForeignKey(default=django.contrib.auth.models.User, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
