# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-14 12:26
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0035_auto_20171213_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companycomment',
            name='user',
            field=models.CharField(default=django.contrib.auth.models.User, max_length=250),
        ),
    ]
