# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-07 10:01
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_post_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default=None, max_length=128),
        ),
    ]
