# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-07 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_auto_20171207_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comment',
            field=models.CharField(default='', max_length=500),
        ),
    ]
