# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-07 13:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_auto_20171207_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
    ]
