# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-07 14:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import login.models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0020_auto_20171207_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post_id',
            field=models.ForeignKey(default=login.models.Post, on_delete=django.db.models.deletion.CASCADE, to='login.Post'),
        ),
    ]
